-- SEQUENCE : 순차번호 생성기. 대부분 인위적인 PK 사용 용도
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    START WITH 1 -- 부터 시작
    INCREMENT BY 1
    MAXVALUE 999
    MINVALUE 1
    NOCYCLE
    NOCACHE;
SELECT FRIEND_SEQ.NEXTVAL FROM DUAL;  -- 다음 순차번호 값
SELECT FRIEND_SEQ.CURRVAL FROM DUAL;  -- 현재 시퀀스 값

DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    NO NUMBER(5) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    TEL VARCHAR2(20) UNIQUE,
    ADDRESS VARCHAR2(250),
    LAS_MONDIFT DATE DEFAULT SYSTEM
    );
DROP SEQUENCE FRINED_SEQ;
-- 1. Sequence 생성
CREATE SEQUENCE FRIEND_SEQ
    START WITH 1         -- 시작 값
    INCREMENT BY 1       -- 증가 값
    MAXVALUE 99999       -- 최대값
    NOCACHE              -- 캐시하지 않음
    NOCYCLE;             -- 순환하지 않음

-- 2. FRIEND 테이블 생성 (만약 FRIEND 테이블이 없다면)
CREATE TABLE FRIEND (
    NO NUMBER PRIMARY KEY,  -- NO는 기본 키로 설정
    NAME VARCHAR2(50),
    TEL VARCHAR2(20),
    ADDRESS VARCHAR2(100)
);

-- 3. 데이터 삽입
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, '홍길동', '010-9999-9999', '서울');
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, '유길동', NULL, '서울');

-- 4. 데이터 조회
SELECT * FROM FRIEND;

-- 연습문제 --
-- 기존 테이블과 시퀀스 삭제
DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;
DROP SEQUENCE MEMVER_SQE;

-- MEMBER_LEVEL 테이블 생성
CREATE TABLE MEMBER_LEVEL (
    LEVELNO NUMBER(5) PRIMARY KEY,  -- LEVELNO 기본 키
    LEVELNAME VARCHAR2(30)          -- LEVELNAME (레벨 이름)
);

-- MEMBER 테이블 생성
CREATE TABLE MEMBER (
    MNO NUMBER(5) PRIMARY KEY,     -- MNO 기본 키
    MNAME VARCHAR2(50),            -- MNAME (회원 이름)
    MPW VARCHAR2(50),              -- MPW (비밀번호)
    MMAIL VARCHAR2(50),            -- MMAIL (이메일)
    MPOINT VARCHAR2(1000),           -- MPOINT (포인트, NUMBER 타입으로 수정)
    MRADATE DATE,                  -- MRADATE (가입일, DATE 타입으로 수정)
    LEVELNO NUMBER(5),             -- LEVELNO (레벨 번호, MEMBER_LEVEL 참조)
    FOREIGN KEY(LEVELNO) REFERENCES MEMBER_LEVEL(LEVELNO)  -- 외래 키 설정
);

-- 시퀀스 생성
CREATE SEQUENCE MEMBER_SQE 
    START WITH 1         -- 시작 값
    INCREMENT BY 1       -- 증가 값
    MAXVALUE 9999        -- 최대값 설정
    NOCACHE              -- 캐시하지 않음
    NOCYCLE;             -- 순환하지 않음

-- MEMBER_LEVEL 테이블에 데이터 삽입
INSERT INTO MEMBER_LEVEL (LEVELNO, LEVELNAME) VALUES (-1, '검정');
INSERT INTO MEMBER_LEVEL (LEVELNO, LEVELNAME) VALUES (0, '일반');
INSERT INTO MEMBER_LEVEL (LEVELNO, LEVELNAME) VALUES (1, '실버');
INSERT INTO MEMBER_LEVEL (LEVELNO, LEVELNAME) VALUES (2, '골드');

-- MEMBER_LEVEL 데이터 확인
SELECT * FROM MEMBER_LEVEL;

-- MEMBER 테이블에 데이터 삽입
-- 'AA'와 'BB'는 작은따옴표로 감싸야 하며, 날짜 값은 TO_DATE로 변환해야 합니다
INSERT INTO MEMBER (MNO, MNAME, MPW, MMAIL, MPOINT, MRADATE, LEVELNO)
VALUES (MEMBER_SQE.NEXTVAL, '홀길동', 'AA', 'HONG@HONG.COM', 0, TO_DATE('2024/09/26', 'YYYY/MM/DD'), 0);

INSERT INTO MEMBER (MNO, MNAME, MPW, MMAIL, MPOINT, MRADATE, LEVELNO)
VALUES (MEMBER_SQE.NEXTVAL, '신길동', 'BB', 'SIN@SIN.COM', 1000, TO_DATE('2022/04/01', 'YYYY/MM/DD'), 1);


SELECT * FROM MEMBER;

SELECT 
    MEMBER.MNO, 
    MEMBER.MNAME, 
    MEMBER.MRADATE, 
    MEMBER.MMAIL, 
    MEMBER.MPOINT, 
    MEMBER_LEVEL.LEVELNAME
FROM 
    MEMBER, MEMBER_LEVEL
WHERE 
    MEMBER.LEVELNO = MEMBER_LEVEL.LEVELNO;

