-- ※ DML 연습문제 PDF 4PAGE
-- DROP 순서는 자식 테이블부터
DROP TABLE STUDENT;
DROP TABLE MAJOR;
CREATE TABLE MAJOR(
    mCODE NUMBER(2) PRIMARY KEY,
    mNAME VARCHAR2(50) UNIQUE,
    mOFFICE VARCHAR2(200));
CREATE TABLE STUDENT(
    SNO    NUMBER(5) PRIMARY KEY,
    sNAME  VARCHAR2(50) ,
    sSCORE NUMBER(3) CHECK (sSCORE BETWEEN 0 AND 100),
    mCODE  NUMBER(2) REFERENCES MAJOR(mCODE) );

DROP TABLE STUDENT;
DROP TABLE MAJOR;
CREATE TABLE MAJOR(
    mCODE NUMBER(2),
    mNAME VARCHAR2(50),
    mOFFICE VARCHAR2(255),
    PRIMARY KEY(mCODE));
CREATE TABLE STUDENT(
    sNO VARCHAR2(10),
    sNAME VARCHAR2(50),
    sSCORE NUMBER(3),
    mCODE NUMBER(2),
    PRIMARY KEY(sNO),
    CHECK (sSCORE>=0 AND sSCORE<=100),
    FOREIGN KEY(mCODE) REFERENCES MAJOR(mCODE));
    
INSERT INTO MAJOR VALUES (1, '컴퓨터공학','A101호');
INSERT INTO MAJOR VALUES (2, '빅데이터','A102호');
SELECT * FROM MAJOR;
INSERT INTO STUDENT VALUES ('101','홍길동', 99, 1);
INSERT INTO STUDENT VALUES ('102','신길동',100, 2);
INSERT INTO STUDENT VALUES ('103','신길동',-9, 2); -- CHECK 제약조건
INSERT INTO STUDENT VALUES (NULL,'신길동',90, 3);  -- PK 제약조건=(NOT NULL+UNIQUE), FK
SELECT SNO 학번, SNAME 이름, SSCORE 점수, S.MCODE 학과코드, MNAME 학과명, MOFFICE 학과사무실
    FROM STUDENT S, MAJOR M 
    WHERE S.mCODE=M.mCODE;